services:
  caddy:
    image: liuweitao/caddy-webdav:latest # Changed image name
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data # Caddy data, including certificates
      - ./config:/config # Caddy configuration
      - ./webdav_data:/srv/webdav # WebDAV data directory
    environment:
      - CLOUDFLARE_API_TOKEN=your_cloudflare_api_token # Keep if using Cloudflare for TLS
    restart: unless-stopped
