services:
  adb:
    image: liuweitao/adb:latest
    container_name: adb
    volumes:
      - ./apks:/workspace/apks  # 映射本地apk文件夹到容器内
      - /dev/bus/usb:/dev/bus/usb  # USB设备映射
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    privileged: true  # 允许访问USB设备
    restart: unless-stopped  # 除非手动停止，否则总是重启 