name: Build Laravel Nginx Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

env:
  UID: 1000
  GID: 1000

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check latest Nginx version
        id: check_version
        run: |
          LATEST_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/library/nginx/tags?page_size=100&name=stable-alpine" | jq -r '.results[].name' | grep -E '^stable-alpine[0-9.]+$' | sort -V | tail -n1)
          if [ -z "$LATEST_VERSION" ]; then
            echo "Failed to fetch latest Nginx stable-alpine version"
            echo "API Response:"
            curl -s "https://hub.docker.com/v2/repositories/library/nginx/tags?page_size=100&name=stable-alpine" | jq '.'
            exit 1
          fi
          echo "Latest Nginx version: $LATEST_VERSION"
          
          if [ ! -f .nginx-version ]; then
            echo "No .nginx-version file found, creating it with the latest version"
            echo "$LATEST_VERSION" > .nginx-version
            echo "BUILD_NEEDED=true" >> $GITHUB_ENV
            echo "NGINX_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          else
            CURRENT_VERSION=$(cat .nginx-version)
            if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
              echo "New version found. Current: $CURRENT_VERSION, Latest: $LATEST_VERSION"
              echo "BUILD_NEEDED=true" >> $GITHUB_ENV
              echo "NGINX_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
            else
              echo "Version is up to date. Current: $CURRENT_VERSION"
              echo "BUILD_NEEDED=false" >> $GITHUB_ENV
            fi
          fi

      - name: Debug environment variables
        run: |
          echo "BUILD_NEEDED: ${{ env.BUILD_NEEDED }}"
          echo "NGINX_VERSION: ${{ env.NGINX_VERSION }}"
          echo "UID: ${{ env.UID }}"
          echo "GID: ${{ env.GID }}"

      - name: Build and push Docker image
        if: env.BUILD_NEEDED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./laravel/nginx
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/laravel-nginx:${{ env.NGINX_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/laravel-nginx:latest
          build-args: |
            NGINX_VERSION=${{ env.NGINX_VERSION }}
            UID=${{ env.UID }}
            GID=${{ env.GID }}

      - name: Update version file
        if: env.BUILD_NEEDED == 'true'
        run: echo ${{ env.NGINX_VERSION }} > .nginx-version

      - name: Commit and push if version changed
        if: env.BUILD_NEEDED == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .nginx-version
          git commit -m "Update Nginx version to ${{ env.NGINX_VERSION }}"
          git push
