name: Build Xray Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Xray version'
        required: true
        type: string
  schedule:
    - cron: '0 0 * * 0'

env:
  REGISTRY: docker.io
  IMAGE_NAME: liuweitao/xray

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest version
        if: github.event_name == 'schedule'
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r .tag_name | sed 's/v//')
          echo "VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Set manual version
        if: github.event_name == 'workflow_dispatch'
        run: echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: xray
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }} 