name: Build FRP Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest changes and update local repository
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin master
          git reset --hard origin/master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check for new FRP version
        id: check-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | grep 'tag_name' | cut -d\" -f4 | sed 's/v//')
          echo "Latest FRP version: $LATEST_VERSION"
          
          if [ -f .frp-version ]; then
            CURRENT_VERSION=$(cat .frp-version)
          else
            CURRENT_VERSION=""
          fi
          
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "New version detected"
            echo "BUILD_NEEDED=true" >> $GITHUB_ENV
            echo "FRP_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          else
            echo "No new version"
            echo "BUILD_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Build and push FRP Server Docker image
        if: env.BUILD_NEEDED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frp
          file: ./frp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frps:${{ env.FRP_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frps:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            VERSION=${{ env.FRP_VERSION }}
            TYPE=s

      - name: Build and push FRP Client Docker image
        if: env.BUILD_NEEDED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frp
          file: ./frp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frpc:${{ env.FRP_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frpc:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            VERSION=${{ env.FRP_VERSION }}
            TYPE=c

      - name: Update version file
        if: env.BUILD_NEEDED == 'true'
        run: echo ${{ env.FRP_VERSION }} > .frp-version

      - name: Commit and push if version changed
        if: env.BUILD_NEEDED == 'true'
        run: |
          git add .frp-version
          git commit -m "Update FRP version to ${{ env.FRP_VERSION }}"
          git push origin master
