name: Build Laravel PHP 7.4 Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'laravel/php7.4/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./laravel/php7.4
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-php:7.4
        build-args: |
          UID=1000
          GID=1000
